name: Autodeploy to GitHub Pages

on:
  push:
    branches:
      - master

permissions: # <--- ¡¡¡AÑADE ESTA SECCIÓN AQUÍ!!!
  contents: write # Permite al bot escribir en el repositorio
  pages: write    # Permite al bot gestionar despliegues de GitHub Pages
  id-token: write # Necesario si GitHub Pages usa autenticación OIDC, buena práctica incluirlo.

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Git
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        # Esta línea puede ser simplificada si se usa el método de acciones/checkout con token
        # o si los permisos son correctos. Pero la mantendremos por ahora si está funcionando.
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

    - name: Delete gh-pages branch from remote
      run: |
        # Añadir '&& true' o '|| true' para que el workflow no falle si la rama no existe
        git push origin --delete gh-pages || true

    - name: Create new gh-pages branch
      run: |
        git checkout --orphan gh-pages

    - name: Add all files to gh-pages
      run: |
        git add --all
        git commit -m "Deploy to gh-pages"

    - name: Push to gh-pages branch
      run: |
        git push origin gh-pages --force
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}